### ISSUE TITLE
Error after r2pm -i r2pipe-py

### ISSUE THREAD

**Issue by fr0ster** [radareorg/radare2-r2pipe#121]
**Describe the issue**

Can't install r2pipe

**How to reproduce?**

$r2pm -i r2pipe-py
r2pm -i r2pipe-py                                                                                                                              vagrant@vagrant
Install Done For r2pipe-py
/usr/lib/python2.7/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  from cryptography.utils import int_from_bytes
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Defaulting to user installation because normal site-packages is not writeable
Collecting r2pipe
  Using cached r2pipe-1.5.0.tar.gz (8.7 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-kcTMg9/r2pipe/setup.py'"'"'; __file__='"'"'/tmp/pip-install-kcTMg9/r2pipe/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-gKlTuW
         cwd: /tmp/pip-install-kcTMg9/r2pipe/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-kcTMg9/r2pipe/setup.py", line 3, in <module>
        import r2pipe
      File "r2pipe/__init__.py", line 38, in <module>
        from r2pipe.open_sync import open
      File "r2pipe/open_sync.py", line 15, in <module>
        from urllib.error import URLError
    ImportError: No module named error
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Expected behavior**

I want to get working plugin

**Possible fix**

I can't install it for python3 as pip3 install r2pipe

**Comment by trufae** [comment]
Theres a repo for r2pipe. This is not the right repo to fill this issue. Also, py2 support was removed one year ago. Whats the error you get with pip3?
