### ISSUE TITLE
macOS Big Sur "pip install r2pipe" not working

### ISSUE THREAD

**Issue by HeyWatchOutDude** [radareorg/radare2-r2pipe#130]
Hi,

im unable to install "pip install r2pipe" on macOS Big Sur (11.2.1)

Error message:
![error](https://user-images.githubusercontent.com/61534143/108273656-2375cd80-7174-11eb-8a9b-d1168874d392.PNG)

Is that a known issue?

**Comment by a1ext** [comment]
It seems you are using Python 2, please use Python 3 with `pip3 install r2pipe`

**Comment by HeyWatchOutDude** [comment]
Thanks please close the case!

**Comment by trufae** [comment]
You mean to close this issue?
