### ISSUE TITLE
qt code example will not link properly with radare2

### ISSUE THREAD

**Issue by josephkehoe** [radareorg/radare2-r2pipe#131]
## Environment

22/02/2021
radare2 4.3.1 6 @ windows-x86-64 git.4.3.1
commit: 54ac837b5503f10f91e2069ac357791f7a3e635a build: Fri 03/06/2020__15:52:24.93
Windows 10 Education
1.5.3

## Description

When the QT example code is compiled in using QT6 it compiles but fails when linking with 19715 errors like the following:

error: undefined reference to `r_config_get'
C:\Users\KEHOEJ\AppData\Local\Programs\radare2\lib\libr_core.a(f105261@@r_core@sta\core.c.obj):-1: 

It cannot find *any* functions in the .a libraries (but it does find the libraries).  I installed the windows exe and did not compile from source code

**Comment by trufae** [comment]
R2 4.3 is really old. Use the 5.x ones or git master. One reason for not finding the symbols could be using the 32bit sdk on 64bit linkage and viceversa

**Comment by josephkehoe** [comment]
Hi,

Thanks for the very prompt response.  I have done as you said (installed a more recent radare2 binary) and that solved the problem.

Your help is appreciated.

Thanks again,
Joseph.
