### ISSUE TITLE
[python3] r2.quit() hangs execution

### ISSUE THREAD

**Issue by scmanjarrez** [radareorg/radare2-r2pipe#135]
## Environment
Python 3.8.11

lun ago 16 13:14:15 CEST 2021
radare2 5.4.0-git 26650 @ linux-x86-64 git.5.4.0-git
commit: b0d8f6d3fc1262033af8d7366d99566958c6f9cb build: 2021-08-16__12:53:05
Linux x86_64
1.5.3

## Description
Exiting r2 with quit() hangs the program.

## Test
```bash
pip3 install r2pipe
python3
>>> import r2pipe
>>> r2 = r2pipe.open('/bin/ls')
>>> print(r2.cmd('?e Hello World'))
Hello World
>>> r2.quit()
```

![Peek 2021-08-16 13-24](https://user-images.githubusercontent.com/9284124/129556420-2c4df296-8c27-469d-ac22-51329fa525cc.gif)

**Comment by radare** [comment]
can you pip install -UI r2pipe and try again?

**Comment by scmanjarrez** [comment]
Hi, thank you very much. Version 1.5.5. now exits correctly. Closing issue.

**Comment by trufae** [comment]
Awesome! i found another issue and i'm fixing it, so expect 1.5.6 to be published soon. Thanks for reporting! We surely need to add more r2pipe tests in the main repo.
