### ISSUE TITLE
test-pipe.c:1:10: fatal error: r_socket.h: No such file or directory

### ISSUE THREAD

**Issue by Oliver-zrz** [radareorg/radare2-r2pipe#142]
## Environment
radare2 5.4.3 26925 @ linux-x86-64 git.5.4.2
commit: 65448811e5b9582a19cf631e03cfcaa025a92ef5 build: 2021-10-30__18:51:09

## Problem
When I compiled test-pipe.c, the following error appeared. I'm here for some help, could you analyse this problem and teach me how to solve it, please?
```
$ make
make: pkg-config: Command not found
make: pkg-config: Command not found
cc -o test-pipe test-pipe.c  
test-pipe.c:1:10: fatal error: r_socket.h: No such file or directory
 #include <r_socket.h>
          ^~~~~~~~~~~~
compilation terminated.
Makefile:9: recipe for target 'test-pipe' failed
make: *** [test-pipe] Error 1
```

**Comment by trufae** [comment]
You have to install pkg-config

**Comment by Oliver-zrz** [comment]
It works, thank you very much

**Comment by Oliver-zrz** [comment]
It works, thank you very much

**Comment by Oliver-zrz** [comment]
It works, thank you very much

**Comment by Oliver-zrz** [comment]
It works, thank you very much
