### ISSUE TITLE
If possible, please release the latest release version

### ISSUE THREAD

**Issue by kawhiLin** [radareorg/radare2-r2pipe#162]
Due to organization restrictions, i can only use the release version. The current release version r2pipe is 1.7.1 (tag==5.7.0), which has some bugs compared with the 1.9.4 version of the master branch. 
If possible, please release the latest release version. It will helps me a lot, thanks : )

**Comment by trufae** [comment]
uhm. but you can pick the one from pip, isnt? ill cut a release here its been forgotten for quite a while indeed :D

**Comment by trufae** [comment]
done
