### ISSUE TITLE
Bug in argument of -d

### ISSUE THREAD

**Issue by Maijin** [radareorg/radare2-r2pipe#71]
`r2 = r2pipe.open(["-d","AAABBB"])` is debugging the argument instead of the binary via @bannsec

From https://github.com/radare/radare2/issues/11341

**Comment by radare** [comment]
Thats not a bug. Thats a bad usage of the api

**Comment by trufae** [comment]
What about doing r2pipe.open("ls -l", ["-d"]) instead?
